services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: testapi
    ports:
      - "3307:3306"
    networks:
      - apinet

  api:
    build:
      context: ./ApiProductos/ApiProductos
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: api
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=testapi;User ID=root;Password=12345678;allowPublicKeyRetrieval=True;"
    depends_on:
      - mysql
    command: sh -c "until mysql -h mysql -u root -p12345678 -e 'SELECT 1'; do echo 'Waiting for MySQL...'; sleep 2; done; dotnet ef database update; dotnet ApiProductos.dll"
    networks:
      - apinet

networks:
  apinet:
